/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/airplanetib/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.planetibet.geometry} material={materials['Material.001']} rotation={[0.032, -0.021, 0.162]} />
      <mesh geometry={nodes.PUSHILIN_Plane_Helix001.geometry} material={materials.plane} position={[0.983, 0.226, 0.013]} />
    </group>
  )
}

useGLTF.preload('/model.glb')
